version: '3'

# includes:
#   checksum: ./Taskfile_checksum_{{OS}}.yml 

tasks:
  build:
    cmds:
      - >
        go build -v -trimpath 
        --ldflags "-X main.version=$VERSION" 
        -o {{.BUILD_NAME}}
    env:
      VERSION: dev
      OS: "{{OS}}"
      ARCH: "{{ARCH}}"
      CGO_ENABLED: 1
    vars:
      BUILD_NAME:
        sh: task build:name

  build:name:
    cmds:
      - task: "build:name:{{OS}}-{{ARCH}}"

  build:name:linux-amd64:
    cmds:
      - echo "2ami-$VERSION-linux-amd64"
    env:
      VERSION: dev

  build:name:macos-11-amd64:
    cmds:
      - echo "2ami-$VERSION-linux-amd64"
    env:
      VERSION: dev

  build:name:Windows_NT-amd64:
    cmds:
      - echo "2ami-$VERSION-windows-amd64"
    env:
      VERSION: dev

  checksum:upload:
    cmds:
      - gh release upload $VERSION ./checksum-2ami-$VERSION-$OS-$ARCH.txt
    env:
      VERSION: dev
      OS: "{{OS}}"
      ARCH: "{{ARCH}}"
    preconditions:
      - sh: "[ -n \"$GITHUB_TOKEN\" ]"
        msg: "GITHUB_TOKEN must be set"

  release:upload:
    cmds:
      - gh release upload $VERSION ./2ami-$VERSION-$OS-$ARCH{{exeExt}}
    env:
      VERSION: dev
      OS: "{{OS}}"
      ARCH: "{{ARCH}}"
    preconditions:
      - sh: "[ -n \"$GITHUB_TOKEN\" ]"
        msg: "GITHUB_TOKEN must be set"