#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

# if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
#   brew bundle check >/dev/null 2>&1  || {
#     echo "==> Installing Homebrew dependencies…"
#     brew bundle
#   }
# fi

go_version=$(cat ".tool-versions")

if asdf list golang | grep "$go_version" 2>&1 >/dev/null; then
  echo "==> Installing Golang version…"
  asdf install golang $go_version
fi

if [ -f "go.sum" ]; then
  echo "==> Installing go dependencies…"
  GO111MODULE=on go mod vendor
fi